# Generated by Django 4.2.7 on 2023-11-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_api', '0002_alter_artist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='work',
            field=models.ManyToManyField(related_name='artists', to='artist_api.work'),
        ),
    ]
