# Generated by Django 4.2.7 on 2023-11-30 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artist_api', '0005_alter_artist_works'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='works',
            new_name='work',
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
